### ISSUE TITLE
add how to play instruction in landingpage

### ISSUE THREAD

**Issue by Aashray446** [Aashray446/DSA_MADE_EASY#5]
page - Index.html , add instruction that looks good as well

**Comment by Michele971** [comment]
How can we run the repo?

**Comment by Aashray446** [comment]
> How can we run the repo?

You can directly clone it and open the index.html. For simplicity, we have not used any frontend framework. The project is in the very infant stage.

**Comment by Michele971** [comment]
Done! You have a new Pull Request :)

**Comment by Aashray446** [comment]
Thanks for your contribution @Michele971

**Comment by Aashray446** [comment]
Thanks for your contribution @Michele971
